# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.3]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: darkmirage/wireplace-scene
        ref: master
        token: ${{ secrets.FULL_GITHUB_PAT }}
        path: ./wireplace-scene
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./wireplace-scene
    - run: npm run build
      working-directory: ./wireplace-scene
    - run: npm link ./wireplace-scene
    - run: npm install
    - run: npm link ./wireplace-scene
    - run: npm test
    - run: npm run build
